### ISSUE TITLE
API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.

### ISSUE THREAD

**Issue by damien-gaillard** [MobileTribe/delivery-gradle-plugin#8]
Hello,

I'm working on an android project and i got this message when building : 
"`API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.`"

3.3.5 should have solved it, but it didn't. I cloned your project and found the line causing the problem : `variant.assemble.dependsOn += project.tasks.withType(PrepareBuildTask)` in AndroidBuild.groovy Line 47.

I made some test, i replaced it with : 
                  

                    if (variant.hasProperty("assembleProvider")) {
                        variant.assembleProvider.configure {
                            dependsOn(PrepareBuildTask)
                        }
                    } else {
                        variant.assemble.dependsOn += project.tasks.withType(PrepareBuildTask)
                    }

And it fixes the message

**Comment by paillardf** [comment]
You right ! I missed that one that's why the previous fix didn't solve this issue.
Thank you for taking time to investigate. Let me know if the 3.3.6 release fixed it once for all.

**Comment by damien-gaillard** [comment]
It s fixed, thank you !
